# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Sreenidhi Sreesha
tagline:          'Programming blog'
description:      ''
url:              http://sreeshas.github.io
baseurl:          /

author:
  name:           'Sreenidhi Sreesha'
  url:            https://twitter.com/sreeenidhi

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sreeshas
